name: Dev - Content Fly PoJC NFT Token CI / CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"
      - name: Setup Rust toolchain
        run: rustup install stable && rustup default stable && rustup target add wasm32-unknown-unknown
      
      - name: Cache ic-cdk-optimizer
        id: cache-ic-cdk-optimizer
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-ic-cdk-optimizer
      - name: Install IC CDK Optimizer
        if: steps.cache-ic-cdk-optimizer.outputs.cache-hit != 'true'
        run: cargo install ic-cdk-optimizer
      
      - name: Install DFX
        run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        env:
          DFX_VERSION: 0.8.1
      - name: Add DFX identity and wallets
        run: ./ciscripts/add-ic-identity.sh
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}
          DFX_WALLETS: ${{ secrets.DFX_WALLETS }}
      
      - name: Deploy NFT Canister
        run: ./ciscripts/deploynft.sh
        env:
          CANISTER_CAP_ID: ${{ secrets.CANISTER_CAP_ID }}
  

      