name: Dev - Content Fly PoJC NFT Token CI / CD

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"
          cache: "npm"
      - name: Setup Rust toolchain
        run: rustup install stable && rustup default stable && rustup target add wasm32-unknown-unknown
      - name: Install IC CDK Optimizer
        run: cargo install ic-cdk-optimizer
      - name: Install DFX
        run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        env:
          DFX_VERSION: 0.8.1
      - name: Add DFX identity and wallets
        run: ./ciscripts/add-ic-identity.sh
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}
          DFX_WALLETS: ${{ secrets.DFX_WALLETS }}
      - name: Start DFX
        run: dfx start --clean --background
      - name: Start Cap Service
        run: npm run cap:start
        env:
          NODE_ENV: ci
      - name: Test
        run: npm run test
        env:
          CI: 1
          NODE_ENV: ci
      - name: Run Health Check
        run: npm run dip721:healthcheck
        env:
          NODE_ENV: ci

      