name: Test - PoJC NFT Token

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Setup Rust toolchain
        run: rustup install stable && rustup default stable && rustup target add wasm32-unknown-unknown

      - name: Cache agent-rust
        id: cache-agent-rust
        uses: actions/cache@v2
        with:
          path: agent-rust
          key: ${{ runner.os }}-agent-rust-v2
      - name: Install icx cmd
        if: steps.cache-agent-rust.outputs.cache-hit != 'true'
        run: git clone https://github.com/dfinity/agent-rust.git && cd agent-rust && cargo build

      - name: Cache ic-cdk-optimizer
        id: cache-ic-cdk-optimizer
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-ic-cdk-optimizer
      - name: Install IC CDK Optimizer
        if: steps.cache-ic-cdk-optimizer.outputs.cache-hit != 'true'
        run: cargo install ic-cdk-optimizer

      - name: Install DFX for Cap
        run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        env:
          DFX_VERSION: 0.8.4
      - name: Add DFX identity and wallets
        run: ./ciscripts/add-ic-identity.sh
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}
          DFX_WALLETS: ${{ secrets.DFX_WALLETS }}

      - name: Update CAP dfx
        run: ./ciscripts/update-dfx-version.sh
      - name: Start DFX
        run: dfx start --clean --background
      - name: Cache Cap
        id: cache-cap
        uses: actions/cache@v2
        with:
          path: ./cap/target
          key: ${{ runner.os }}-cap-v2
      - name: Build Cap Service
        if: steps.cache-cap.outputs.cache-hit != 'true'
        run: npm run cap:build
        env:
          NODE_ENV: ci
      - name: Start Cap Service
        run: npm run cap:start
        env:
          NODE_ENV: ci

      - name: Setup PATH for icx
        run: echo "./agent-rust/target/debug" >> $GITHUB_PATH
      - name: Run Health Check
        run: npm run dip721:healthcheck
        env:
          NODE_ENV: ci
      - name: Stop DFX
        run: dfx stop
